apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istioflux
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istiorepo
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
    upgrade:
      remediation:
      retries: 3
  values:
    revision: canary
