apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istiorelease
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./istio-1.13.2
  prune: true
